---
- name: install Apache
  become: true
  apt:
    name: apache2
- name: start and enable Apache
  become: true
  service:
    name: apache2
    state: started
    enabled: yes
    daemon_reload: yes
